try {
  alert("test!");
} catch(err) {
  alert(err);
}
